global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'rf_exporter'
    static_configs:
      - targets: ['rf_exporter:8000']